# general configuration
# url: http://excentris.net
url: https://frank-chen.com/
baseurl: ''

# compass configuration
compass:
  # an avatar or logo (optional)
  # logo: "/images/compass.png"
  logo: "/images/20160610_moto_guy_1000x1000_courtesy_bm.jpg"
  # author will appear under the avatar (optional)
  author: "frank"
  # tagline will appear under the title (optional) - currently commented out as tagline in index.html
  tagline: "chen"
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: false
  # Twitter @username (as defined by the Twitter Card specs)
  twitter: "compass"

# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
